#
# Copyright (C) 2024 GeonamesR Package.
#
# GeonamesR Package is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

name: geonamesr

services:
  geonamesr:
    build: .
    container_name: geonamesr
    image: geonamesr/geonamesr:v0.1.0

    ports:
      - "5050:5050"

    volumes:
      - ${PWD}/data:/data
